### ISSUE TITLE
Tests aren't insulated from the network.

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#110]
Currently there are a large number of tests that test networking-related functionality **without** mocking it out. This means that tests will fail in surprising ways on different environments. 

(One example: GCE detection doesn't mock out the network, so we see the behavior intended in the tests in "most" environments, but on GCE we will accidentally pick up the metadata service, and on AWS, we'll see a different codepath as we _can_ fetch `169.254.169.254`, but it won't have the expected Google metadata header.)

This needs to be cleaned up throughout the tests.

**Comment by dhermes** [comment]
:+1:

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
