### ISSUE TITLE
Add support for incremental OAuth 2.0

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#113]
See:
https://developers.google.com/accounts/docs/OAuth2WebServer#incrementalAuth

By sending the query parameter `include_granted_scopes=true`, previous authorizations can be wrapped into new tokens (when new scopes are needed).

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
