### ISSUE TITLE
Mock out implicit behavior so that test_get_application_default_environment_not_set_up always passes

### ISSUE THREAD

**Issue by soltanmm** [google/oauth2client#123]
Fails on some Ubuntu 14.04 LTS machines for both py27 and py34.

**Comment by dhermes** [comment]
Can you include the test failure?

**Comment by dhermes** [comment]
From [the code][1]

> It is normal for this test to fail if run inside a Google Compute Engine VM or after `gcloud auth login` command has been executed on a non Windows machine.

I'm going to see if I can make this pass irrespective of environment.

[1]: https://github.com/google/oauth2client/blob/fd054dcdcc5f6a4d3a0b7a29f410f415f342044c/tests/test_oauth2client.py#L404

**Comment by dhermes** [comment]
@craigcitro Can you re-open. #149 on partially fixed this. I want to use `unittest.mock` to replace all the implicit behavior.

**Comment by dhermes** [comment]
Sorry can you also edit the title to "Mock out implicit behavior so that test_get_application_default_environment_not_set_up always passes"

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
