### ISSUE TITLE
Refresh expired access tokens before waiting for a 401 response

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#135]
new_request potentially makes a request even if self.access_token_expired is True: https://github.com/google/oauth2client/blob/933e1d0073d676d6a80d39616405b19fc6f7ccbd/oauth2client/client.py#L550

If the token is expired, the server will return a 401, new_request will refresh the token, and then it will retry the request.

It should refresh beforehand if the access token is known to be expired, avoiding an unnecessary HTTP call.

**Comment by nathanielmanistaatgoogle** [comment]
Agreed.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
