### ISSUE TITLE
No support for flows that require no redirect_url at all

### ISSUE THREAD

**Issue by lnenov** [google/oauth2client#146]
Recently I had to use a flow that fails if redirect_url is provided.
I monkey patched an oauth2client(1.2) almost like https://github.com/google/oauth2client/commit/a0d99b9168cefcd6dab19ce68e0b59aef7770bfd and it works fine for me. 

But given what a bad practise monkey patching is, it would be great if you can include the possibility to exchange codes without providing any redirect_url.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
