### ISSUE TITLE
issue with AppAssertionCredentials and Python3

### ISSUE THREAD

**Issue by ptone** [google/oauth2client#150]
seem to be a few edge cases for Python3 - seems similar to #106 

https://gist.github.com/ptone/7e45323e91097ed3cc2f

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
