### ISSUE TITLE
ServiceAccountCredentials need way to modify UserAgent after serialization

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#164]
We accept a user_agent in [**init**](https://github.com/google/oauth2client/blob/master/oauth2client/service_account.py#L40) but that doesn't cover deserialization via the Credentials base class from_json method.

Presently to allow for caching, one must need to inherit from the private _ServiceAccountCredentials and hard-code user agent and scopes into to_json / from_json methods.

**Comment by anthmgoogle** [comment]
Agreed. We should add factory overloads to from_stream, but also provide a way to clone the credentials with a changed user agent, so that it can be used with the Default Credentials also. Tracking this bug as part of completing Usable Auth.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
