### ISSUE TITLE
_ServiceAccountCredentials should be public

### ISSUE THREAD

**Issue by thobrla** [google/oauth2client#165]
Until https://github.com/google/oauth2client/issues/164 is addressed, users of service account credentials need to subclass _ServiceAccountCredentials to override the to_json and from_json methods; thus we should expose this class as public so that consumers don't need to inherit from a private class.

**Comment by anthmgoogle** [comment]
Agreed, we should do a review of the surface area and make this public.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
