### ISSUE TITLE
Add a new credential type, IAMCredential

### ISSUE THREAD

**Issue by tbetbetbe** [google/oauth2client#166]
It is constructed with and holds two fields
- iam-token
- iam-authority-selector
  IAMCredential applies these values to requests as a pair HTTP headers (or an equivalents) keys
  - "x-goog-iam-authorization-token"
  - "x-goog-iam-authority-selector"
    respectively

N.B, there is no requirement that an IAMCredential be returned by Application Default Credentials.

**Comment by dhermes** [comment]
@tbetbetbe Is there some Google documentation to brush up on?

**Comment by tbetbetbe** [comment]
Nothing yet, but there are examples in other the google-auth-libraries
- ruby google/google-auth-library-ruby#24
- php google/google-auth-library-php#28

**Comment by dhermes** [comment]
What is the point of adding support for something which doesn't "exist"? Giving end-users a reference to the source instead of documentation is "cowboy coding", no?

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
