### ISSUE TITLE
Add clientsecrets.py ability to report on Errors.

### ISSUE THREAD

**Issue by byuksel** [google/oauth2client#17]
Proposed code change for oauth2client/clientsecrets.py

class InvalidClientSecretsError(Error):
  """Format of ClientSecrets file is invalid."""
  def **init**(self, Error):
    logging.info("Error:"+str(Error))
  pass

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
