### ISSUE TITLE
Suggest supporting passthrough "state" in step1_get_authorize_url

### ISSUE THREAD

**Issue by jorr-at-google** [google/oauth2client#170]
It is good practice to put an anti-forgery token in the "state" field to defend against cross-site attacks. 
See e.g. https://developers.google.com/identity/protocols/OpenIDConnect#accessingtheservice

Suggest enabling this as a kwarg in step1_get_authorize_url.
See: https://github.com/jorr-at-google/oauth2client/commit/a1029673a3f3a541acbed6bc9e46598f7b8122d0

**Comment by bigblind** [comment]
I'd like to see this too.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
