### ISSUE TITLE
test framework is fragile to file permissions changes (+x)

### ISSUE THREAD

**Issue by pcostell** [google/oauth2client#209]

**Comment by dhermes** [comment]
See comments on #208 and #86 for context.

**Comment by pcostell** [comment]
Bringing the conversation here:
 In theory watching for drastic coverage changes could have caught this -- it would have dropped from ~65% to 55%.

**Comment by dhermes** [comment]
That's true. I was writing it off as one less line of code without any new coverage (`(A - 1) / (B -1) < A / B`) without actually looking at the difference between numbers.

A true solution would be 100% code coverage and having coveralls fail if it ever dropped.

**Comment by eamonnmcmanus** [comment]
Actually @dhermes when you looked it really was just one less line of code. I added the regression test later at the request of @nathanielmanistaatgoogle and that's when I screwed up the permissions.

**Comment by dhermes** [comment]
Yeah that's true. I think 100% code coverage makes it fool-proof. Finding a permission change among

![screen_shot_020](https://cloud.githubusercontent.com/assets/520669/8460290/5f52a1dc-1fd8-11e5-808f-02b33eb88912.png)

is not an easy task

**Comment by eamonnmcmanus** [comment]
Oh wow, those are octal permission masks. Live and learn.

**Comment by dhermes** [comment]
Indeed, but no one would even think to look at them during a code review.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
