### ISSUE TITLE
Add better handling for NO_GCE_CHECK

### ISSUE THREAD

**Issue by pcostell** [google/oauth2client#218]
Right now, you have to provide the exact string "True" to NO_GCE_CHECK in order to disable the check. This is somewhat error-prone as it's easy to think you've disabled the check but you actually haven't.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
