### ISSUE TITLE
Implement Decorator 3LO pattern for Django

### ISSUE THREAD

**Issue by anthmgoogle** [google/oauth2client#223]
The OAuth2Decorator pattern has been implemented for the WebApp2Framework. See the class OAuth2Decorator here:
https://github.com/google/oauth2client/blob/master/oauth2client/appengine.py

This pattern if very effective for usability of 3LO and should be extended to other frameworks. This item tracks implementing this pattern for DJango.

**Comment by jonparrott** [comment]
@waprin is working on this.

**Comment by dhermes** [comment]
Thanks!

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
