### ISSUE TITLE
Implement Decorator 3LO pattern for Flask

### ISSUE THREAD

**Issue by anthmgoogle** [google/oauth2client#224]
The OAuth2Decorator pattern has been implemented for the WebApp2Framework. See the class OAuth2Decorator here:
https://github.com/google/oauth2client/blob/master/oauth2client/appengine.py

This pattern if very effective for usability of 3LO and should be extended to other frameworks. This item tracks implementing this pattern for Flask.

**Comment by bigblind** [comment]
Should separate modules be craeted for flask, bottle etc in the oauth2client directory? Or would we create an `integrations` module that contains all of this?

**Comment by dhermes** [comment]
I vote (strongly) for separate modules.

I also vote for approaching this as an opportunity to think about extensibility. In other words, make it so that it's clear and easy for someone to build such an extension (maybe even just build this as extension libraries, e.g. [`requests-oauthlib`][1]).

[1]: https://github.com/requests/requests-oauthlib

**Comment by jonparrott** [comment]
I'm working on this, as I have existing sample code that mostly does this. I'll submit a PR shortly and we can continue discussion there as we flesh this out.
