### ISSUE TITLE
Do a docs pass to make sure all content renders as expected

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#242]
This is a child of #241.

**Comment by dhermes** [comment]
Things that could be added:

- Docstrings on `GOOGLE_*_URI` constants in `oauth2client/__init__.py`

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
