### ISSUE TITLE
Jwt Access Credentials should cache JWTs

### ISSUE THREAD

**Issue by anthmgoogle** [google/oauth2client#254]
The JWT Access Credentials should temporarily cache JWTs. Suggested algorithm:
- Hash JWTs using Audience as key.
- Also store the timestamp of last use with each JWT.
- On access clear any JWT unused for more than 1 hour.

**Comment by dhermes** [comment]
On the instance or module? Threadsafe?

**Comment by anthmgoogle** [comment]
On the instance. It should have the same thread safety as the other credential types.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
