### ISSUE TITLE
Invalid response 400. Error: invalid_scope

### ISSUE THREAD

**Issue by mringg** [google/oauth2client#256]
I found one problem when I began to try auth Google's Service with oauth2client.
The scope is 'https://ddp.googleapis.com/api/ddp/',I can auth that by the api of Java.
The information of problem is,oauth2client.client.OAuth2DeviceCodeError: Invalid response 400. Error: invalid_scope.
tks

**Comment by dhermes** [comment]
Can you provide the code you ran to cause this error?

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
