### ISSUE TITLE
Rollback #264 after Travis-Ci upgrades the default version of pypy to 2.6

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#266]

**Comment by dhermes** [comment]
https://github.com/travis-ci/travis-ci/issues/4756

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
