### ISSUE TITLE
Rework usage of exceptions

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#295]
See comments in https://github.com/google/oauth2client/pull/290 about `AppIdentityError`

> Also `AppIdentityError` does seem like a rather slim class that includes only a fixed message and none of the actual values that led to its generation - would that benefit from being fleshed out a little?

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
