### ISSUE TITLE
Client needs to retry on 502s when requesting refresh token

### ISSUE THREAD

**Issue by sammcveety** [google/oauth2client#315]
This call is expected to be idempotent, and should be retried.

Stack trace ~~track~~:

``` python
<elided>
in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
AccessTokenRefreshError: Invalid response 502.
```

Additional concerns:

Possible conditions include:
HTTP 5xx
HTTP 429
Connection break / socket timeout
Zero-length response from service
httplib errors (bad status line, incomplete read, response not ready)
DNS lookup failure

Possible retry approaches include:
Fail-fast (application prefers to fail as quickly as possible)
Retry N times with exponential backoff to K seconds

**Comment by sammcveety** [comment]
Expected behavior is that if _do_refresh_request gets a 502 from oauth2client/client.py, the containing new_request call from oauth2client/client.py will retry some reasonable number of times.

**Comment by nathanielmanistaatgoogle** [comment]
I'm open to this - how would you suggest the options (fail-fast boolean, N, K, and anything else) be passed from customer code to oauth2client code?

**Comment by dhermes** [comment]
FYI Something (sort of) already exists for a list of status codes to refresh on:

https://github.com/google/oauth2client/blob/237e5d139484c65c2b23a8b5d69056d56ab74b3a/oauth2client/client.py#L76-L77

@nathanielmanistaatgoogle will love that 401 is hard-coded rather than referenced by name as `httplib.UNAUTHORIZED`.

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes: mutable module-scope state? Oh just shove the knife in deeper.

**Comment by dhermes** [comment]
Lulz

**Comment by sammcveety** [comment]
Kwargs with sane defaults?

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
