### ISSUE TITLE
[FR] Useful storage for web applications.

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#319]
Currently, we have the following storage classes:

* ``appengine.StorageByKeyName``, which is of course particular to GAE and Datastore.
* ``django_orm.Storage``, which appears to be a port of ``StorageByKeyName`` to Django's ORM.
* ``flask_util.FlaskSessionStorage``.
* ``file.Storage``, ``keyring_storage.Storage``, and ``multistore_file.Storage`` which are not useful in a web application context.

We really don't have a good set of general-purpose storage classes for web applications. I propose a set of new storage classes to make usage of the ``flask_util`` and incoming``django_util`` and ``bottle_util`` easier. Myself and @waprin are willing to implement these, we just want to make sure we're on the right track and that these will be welcome additions.

/cc @dhermes @anthmgoogle

### `storage.DictionaryStorage`

Similar to `StorageByKeyName`, but will write to any object with a dictionary-like interface. This will be used to implement storage for Flask, Django, and other web frameworks' ``session`` object easily.

```python
storage = DictionaryStorage(flask.session, key='google_oauth2_credentials') 
```

### `storage.KeyValueStorage`

Again, similar to `StorageByKeyName`, but will write to any object with ``get(key)``, ``set(key, value)`` and, ``delete(key)`` methods. This will be used to provide storage for redis, memcache, and other kv-stores.

```python
r = redis.StrictRedis()
key = "google_oauth2_credentials_{}".format(flask.session['user_id'])
storage = KeyValueStorage(r, key=key)
```

### App Engine changes

We'll create two new storage classes ``NdbStorage`` and ``DbStorage`` that will default the model to the existing ``CredentialsNDBModel`` and ``CredentialsModel``

Finally, `OAuth2Decorator` will be modified to accept a `storage` argument and only use the existing `_storage_class`, `_credentials_class `, and `_credentials_property_name` for backwards-compatibility.

### `storage.CloudDatastoreStorage`

Uses ``gcloud-python`` to store the credentials, similar usage to ``KeyValueStorage``.

```python
ds = gcloud.datastore.Client()
key = flask.session['user_id']
storage = CloudDatastoreStorage(ds, key=key)
```

### `storage.SqlAlchemyStorage`

Uses sqlalchemy to store the credentials. I haven't given this much thought, but it'll likely be similar to the Django ORM storage.

## Implementation / usage suggestions

For all classes that accept ``key`` argument, it should be possible to specify a string or zero-argument callable. This will allow user-defined functions that can ascertain the key:

```python
def get_key_from_user():
    return users.get_current_user().user_id

storage = KeyValueStorage(google.appengine.api.memcache, key=key)
```

The `*_util` helper classes should accept a ``Storage`` instance or a callable that returns a storage class.  The helper class will pass in the relevant context for the given framework (such as the request). This provides even greater control over the storage:

```python
def get_storage_for_gitkit_user(request):
   gitkit_user = gitkit_instance.VerifyGitkitToken(request.cookies['gtoken'])
   key = 'google-oauth2-credentials-{}'.format(gitkit_user.email)
   return KeyValueStorage(redis_instance, key=key)


oauth2 = flask_util.UserOAuth2(app, storage=get_storage_for_gitkit_user)
```

**Comment by dhermes** [comment]
ISTM we may need to start thinking about a story for `oauth2client` "plugins" and maybe put them elsewhere? (e.g. https://github.com/maraujop/requests-oauth)

----

A crucial chunk of all the `Storage` classes is atomicity. They all have `locked_VERB()` methods and implement them in there relevant domain.

----

Also, earlier this week I was looking at the `django_orm.Storage` implementation and it doesn't actually seem to do what it's supposed to.

**Comment by jonparrott** [comment]
> ISTM we may need to start thinking about a story for oauth2client "plugins" and maybe put them elsewhere?

I'm for this, but I still think we should implement a `DictionaryStorage` and `KeyValueStorage` here.

> A crucial chunk of all the Storage classes is atomicity. They all have locked_VERB() methods and implement them in their relevant domain.

Noted. This is useful in situations where multiple users can cause contention on the storage resource, such as storing multiple credentials in a single file. If I'm understanding correctly, the two most common cases do not need explicit locking. Session storage is already thread-local in most* web frameworks, and is per-user. Storing in a database typically uses a unique key per user so the issue of contention isn't a factor there.

> Also, earlier this week I was looking at the django_orm.Storage implementation and it doesn't actually seem to do what it's supposed to.

D'oh. What does it not do that it should do?

**Comment by dhermes** [comment]
> D'oh. What does it not do that it should do?

AFAICT it conflates the field name on the model class with the key name in the DB for the credentials object.

**Comment by jonparrott** [comment]
Alrighty, so what sort of plan would be acceptable to you at this point? We can take it in small, incremental pieces, starting with:

*  A PR for `DictionaryStorage`, with optional locking, and updating `flask_util` to use that instead of its own storage.
* A PR for `KeyValueStorage`.
* A PR to perform the noted changes to `appengine`.

We can hold off on the other stuff (`CloudDatastoreStorage`, `SqlAlchemyStorage`) until we figure out how/if to handle plugins. If we decide to handle plugins, we can move `appengine`, `flask_util`, `django_orm`, `django_util`, and `bottle_util` into plugins.

(My recommendation for 'plugins' is to maybe have a `contrib` module like `urllib3`)

**Comment by dhermes** [comment]
I like letting `requests` / `urllib3` be our guide.

This plan SGTM

**Comment by waprin** [comment]
@jonparrott , know you are busy with PyCon prep atm but I did another pass at this so give me your thoughts when you're free.

So I started the PR to allow the Django util to actually store credentials in the ORM (Model storage). I think previously, the use case of CredentialsField and FlowField was to provide storage in the absence of a session to do the whole flow. This blog post has snippets which I presume is the use case:

http://www.marinamele.com/use-the-google-analytics-api-with-django

As you can see she is rolling her own flow, and I think the main point of the decorators was to avoid making users roll their own. Now the question might be raised, why don't we just expect users to always use the session to store credentials? I think usually we should, but I think the remaining use case of CredentialsField is when you are not relying on Google auth as your primary form of auth, but rather want to associate Google oauth2 credentials with your existing Django user system. 

Now even with the session storage in Django, there was no easy way to "initialize" the storage ahead of time because it needed the request context to get into the session, forcing me to make a little factory that gets called each time the flow starts:

```
def get_storage(request):
        return DictionaryStorage(request.session, key=_CREDENTIALS_KEY)

```

Now I added an if statement in there so you can do something like this:

```
def get_storage(request):
   if storage_model:
        module_name, class_name = storage_model.rsplit('.', 1)
        module = import_module(module_name)
        storage_model_class = getattr(module, class_name)
        return storage.DjangoORMStorage(storage_model_class,
                                        user_property,
                                        request.user,
                                        credentials_property)
  else: 
         return DictionaryStorage(request.session, key=_CREDENTIALS_KEY)
```

DjangoORMStorage is just django_orm.Storage renamed.

As you can see, in the config you specify your model, which should contain a CredentialsField and a UserField. The helper looks for a User that matches the request.user, and stores the Credentials on the property matching credentials_property.

Advantages:

1. Users rolling their own oauth flow to store credentials using CredentialsField no longer have to
2. Designed to simplify the most common uses cases (using Google auth with sessions and adding Google auth to existing user system)

Disadvantages:

1. In order for "request.user" to be meaningful, the user has to be logged in, adding a bunch of special case code to verify it is for the Model storage (but not for the session storage)
2. Config is a little awkward and relies on dynamic loading of the class
3. Since I need to tweak some of these classes a bit, we either break backwards compatibility or have a few similar looking classes
4. Looking at all of this, I'm wondering if as a Django user wanting to hook up credentials to my user, if it's not easier to just use the helper to get into the session, then copy it from the session to the model manually
5. Documentation will have to get improved to explain these alternatives, plain "credentials go into the session" is simpler to understand

Looking at this, I'm 50/50 on whether the PR is even a good idea, leaning against it.

@theromis , I would appreciate any thoughts on this if you have any, and whether it lines up with your current usage of CredentialsField and django_util.storage (i.e. are you really just using it to hook up a Credential to request.user).

**Comment by waprin** [comment]
Here is the initial sketch of what I was talking about:

https://github.com/waprin/oauth2client/compare/django_110...waprin:refactor?expand=1

In terms of using it, they have something like this in their models: 


```
class CredentialsModel(models.Model):
    user_id = models.OneToOneField(User)
    credential = CredentialsField()
```

then something like this in the settings:
```

GOOGLE_OAUTH2_STORAGE_MODEL = {
    'model': 'polls.models.CredentialsModel',
    'user_property': 'user_id',
    'credentials_property': 'credential'
}
```

with this configed, instead of putting the credentials in the session, it will store them on the credentials_property of the model where request.user == user_property of the model.

**Comment by jonparrott** [comment]
@waprin this sounds good to me, and very reasonable. It seems we optimize for the common case (session credentials) and allow for second common case (database credentials). I'm happy to review those PRs.

**Comment by jonparrott** [comment]
I feel like this is sufficiently satisfied for now.
