### ISSUE TITLE
Avoid use of pickle

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#323]
See https://github.com/google/oauth2client/pull/322/files#r41799308

Will require making `Flow` objects serializable / de-serializable in some other way (e.g. JSON).

**Comment by elenberg** [comment]
@dhermes Have there been any updates in regards to this? Are flow objects serializable in ways other than pickle?

**Comment by dhermes** [comment]
Nope

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
