### ISSUE TITLE
Why new credentials records are created instead of overwriting an existing one when user does not actually have to re-authorize?

### ISSUE THREAD

**Issue by yushkovskiy** [google/oauth2client#327]
I talking about this line
[https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L891](https://github.com/google/oauth2client/blob/00c7773f3109d3bf9bb0438c9a007d970ece5456/oauth2client/client.py#L891)
Maybe it is better to do `self.store.locked_put(self, overwrite=True)`

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
