### ISSUE TITLE
Please add per-file licenses

### ISSUE THREAD

**Issue by petrcermak** [google/oauth2client#331]
_(Extension of #231 and #232)_

The Chromium project (www.chromium.org) pulls in oauth2client indirectly through the catapult (https://github.com/catapult-project/catapult/) and gsutil (https://github.com/GoogleCloudPlatform/gsutil) source repositories. In order for Chromium to be pulled into various Linux source distributions there's a requirement that all of the third party files pass the Linux <tt>licensecheck</tt> utility. Currently there are many files in the oauth2client repository missing per-file licenses. From a current run of <tt>licensecheck</tt>, they are:

```
$ licensecheck -r . | grep "No copyright"
./tests/test_tools.py: *No copyright* UNKNOWN
./tests/test_util.py: *No copyright* UNKNOWN
./tests/__init__.py: *No copyright* Apache (v2.0)
./oauth2client/__init__.py: *No copyright* UNKNOWN
./samples/call_compute_service.py: *No copyright* UNKNOWN
./samples/googleappengine/call_compute_service_from_gae.py: *No copyright* UNKNOWN
./samples/oauth2_for_devices.py: *No copyright* UNKNOWN
./scripts/run_system_tests.py: *No copyright* UNKNOWN
./scripts/fetch_gae_sdk.py: *No copyright* UNKNOWN
./docs/django_settings.py: *No copyright* UNKNOWN
```

We'd like to ask that per-file licenses be added to these files to make it easier to integrate oauth2client not only into Chromium, but also Linux distributions in general. Thanks.

**Comment by nathanielmanistaatgoogle** [comment]
This smells reasonable but I'm reticent to add accept a requirement for this library that is fundamentally *textual* rather than *behavioral* and that would be difficult or weird to integrate into our test suite.

For `oauth2client/__init__.py`: why is `licensecheck` failing on that file? It sure looks like it has a license header comment the same as any other file.

For all other files: why are those being checked? They're test files and tutorial files and whatnot; why would they be pulled into Chromium and Linux source distributions?

**Comment by petrcermak** [comment]
> For <tt>oauth2client/\_\_init\_\_.py</tt>: why is <tt>licensecheck</tt> failing on that file? It sure looks like it has a license header comment the same as any other file.

Sorry for the confusion. Only files with "UNKNOWN" licenses cause issues in Chromium.

> For all other files: why are those being checked? They're test files and tutorial files and whatnot; why would they be pulled into Chromium and Linux source distributions?

I don't have a good answer for this. In general, Chromium (and its dependencies) tends to pull in whole repositories. I suppose this is to prevent Chromium from depending on the internal folder structure of the repositories.

**Comment by nathanielmanistaatgoogle** [comment]
I'm still confused about `oauth2client/__init__.py`. Is it possible that you're running `licensecheck` against a version of the code prior to 709a106ccff3dd174e69908929db9aeffe8968 (4 August 2015)?

As for pulling in whole repositories: doesn't Chromium have to depend on internal folder structure of third-party codebases in order to accomplish anything useful with them after having pulled them in?

**Comment by petrcermak** [comment]
You're right, the oauth2client pulled in by gsutil in catapult is version 1.4.11: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/third_party/gsutil/third_party/oauth2client/oauth2client/__init__.py

As for pulling in whole repositories: That was only my personal interpretation (which might of course be wrong). I meant that Chromium _only_ has to depend on the _public_ folder structure of the dependency (that the dependency intends to expose).

**Comment by nathanielmanistaatgoogle** [comment]
`src/third_party/catapult/third_party/gsutil/third_party/oauthclient`? What the fish is the story with that?

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
