### ISSUE TITLE
Allow for overriding the GCE metadata service root URL.

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#35]
In particular, there are cases where DNS resolution causes problems -- we need to make this configurable.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
