### ISSUE TITLE
Move contrib to its own repository

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#354]
Once non-core modules have been moved to `contrib`, it should be moved to its own repository, `oauth2client-contrib`.

This would require these changes, in this order:
* A new github repository, `google/oauth2client-contrib` will need to be created.
* `oauth2client-contrib` will be published on pypi as `oauth2client-contrib` and will depend on `oauth2client>=2.0.0`.
* `oauth2client` will need to add the [code necessary](https://docs.python.org/2/library/pkgutil.html#pkgutil.extend_path) to enable it to be used as a namespace package.
* `oauth2client` will add an [extra](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) that installs contrib.
* `oauth2client.contrib` and associated tests will be removed from the source tree.
* Version `2.0.0` of `oauth2client` will need to be released.

Users will then be able to install oauth2client and contrib at once using:

```
pip install oauth2client[contrib]
```

The following bugs/PRs must be closed/merged before the move:
* #353 / #352 - move non-core modules into contrib.
* #351 - DictionaryStorage and storage locking.

**Comment by dhermes** [comment]
:+1:  (e.g. https://pythonhosted.org/Flask-OAuth/)

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle let us know your thoughts.

**Comment by nathanielmanistaatgoogle** [comment]
"it should be moved to its own repository" caught me off-guard. Why? This issue talks about how to go about separating the code but doesn't describe the benefit of doing so. What need is a `contrib` directory in this repository unable to fulfill?

**Comment by dhermes** [comment]
It isn't a core part of the implementation. It is an add-on and the release cycles don't need to be tied together.

**Comment by nathanielmanistaatgoogle** [comment]
I guess, sure, but... it still seems like an awful lot of fuss. Are there situations today in which someone would want to use the core part of `oauth2client` but can't because the presence of `contrib` introduces some encumberance? Does `contrib` drag in a lot of heavy dependencies, or particularly problematic dependencies?

I'm not saying that separating out `contrib` is the *wrong* thing to do; I'm just not yet seeing it motivated by a strong and pressing user need. Fill in for me the parts of the picture that I'm missing?

**Comment by dhermes** [comment]
- The Flask users don't have a strong and pressing need for Django helpers
- The Django users don't have a strong and pressing need for App Engine helpers
- The App Engine users don't have a strong and pressing need for file system helpers

and so on.

The main reason this came up is that @jonparrott and I were discussing de-coupling the release cycles of the core library and the extensions (which are really just mini-libraries all on their own).

**Comment by nathanielmanistaatgoogle** [comment]
I'm feeling more and more like this isn't worth doing, but I promise I won't stop you from doing it.

There are lots of modules in the Python standard library for which I don't have a strong and pressing need, but there's installed on my system along with the rest of Python because their presence isn't a significant burden on me and the library is less work for the maintainers if everything is in one larger package rather than many smaller packages.

Of course "Flask users don't have a strong and pressing need for Django helpers", but how large a cost are they paying if the Django helpers get installed along with the Flask helpers"? And is it a reasonable proposition that publishing two smaller libraries is more work than publishing one larger library?

When you were talking about decoupling the release cycles, is that so that `contrib` can release more frequently or less frequently than `oauth2client`?

**Comment by jonparrott** [comment]
> When you were talking about decoupling the release cycles, is that so that contrib can release more frequently or less frequently than oauth2client?

More frequently.

> Are there situations today in which someone would want to use the core part of oauth2client but can't because the presence of contrib introduces some encumberance? 

No.

> Does contrib drag in a lot of heavy dependencies, or particularly problematic dependencies?

Contrib is all optional dependencies, so no here as well.

There are two real motivating factors here, and I can totally be talked out of this:

1. Splitting core from contrib makes a bit of sense. For example, libraries such as gcloud-python should need only depend only on the core, considering we're recommending the use of GoogleCredentials exclusively in that use case.
2. Although contrib is not large now, we could encourage more activity there. This could lead to the need for faster releases. Really, there isn't much more I feel core needs in terms of functionality. So, core could remain relatively stable compared to the rapid release cycle of contrib.

I actually wasn't thinking of splitting it beyond two packages, @dhermes. All of the helpers would still live in the same place - at least until things get large enough to break up further.

**Comment by dhermes** [comment]
:+1:

**Comment by nathanielmanistaatgoogle** [comment]
I remain reluctantly okay with this; feel free to now proceed with carrying this out.

**Comment by jonparrott** [comment]
I won't be able to get to this until January, so we can all think on it for a while. :)

**Comment by dhermes** [comment]
SGTM

**Comment by jonparrott** [comment]
I no longer want to split contrib into its own repository, I will revisit this concept another time.
