### ISSUE TITLE
Drive.json file creation failure when /Users/<username>/.oauth does not exist

### ISSUE THREAD

**Issue by rothnic** [google/oauth2client#359]
Using v1.5.2 with gspread and df2gspread python libraries. I setup the client secrets file as requested, get the permissions screen, then the web client says successful. However, back on the python side it tries to create a drive.json file, but the .oauth folder does not exist. This results in the auth process failing.

I created the .oauth directory, then tried again, and it worked fine. Failure occurred on [this line in file.py](https://github.com/google/oauth2client/blob/2e5c7cb3f0631329dfd28f64edd4ef827df3d534/oauth2client/file.py#L99)

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
