### ISSUE TITLE
Crash in locked_file:_Win32Opener:open_and_lock (Windows 10, Python 3.5)

### ISSUE THREAD

**Issue by kcarnold** [google/oauth2client#361]
The line
```
service = apiclient.discovery.build('gmail', 'v1', http=credentials.authorize(Http()))
```
caused a "python.exe has stopped working" error in one of our Python environments (Anaconda 2.4.1). I traced the error to [https://github.com/google/oauth2client/blob/master/oauth2client/locked_file.py#L290][1] -- `win32file._get_osfhandle` crashed without providing any useful debugging information.

This happened in a client user's environment, so I didn't get a chance to debug past that point. I was able to work around the crash by setting `sys.modules['win32file'] = None` at load time.

This is not a bug in `oauth2client`, but I'm reporting it here because someone might run into it.

[1]: https://github.com/google/oauth2client/blob/7a0029ef687085878e222d46eaea3f180ba472e2/oauth2client/locked_file.py#L290

**Comment by dhermes** [comment]
Thanks a lot!

**Comment by rkhwaja** [comment]
There's more information on this problem at https://github.com/google/google-api-python-client/issues/139

It's not fixed in by python 3.5.1. It's only a problem on windows 10. I _think_ that it's only a problem with 64-bit python, although I haven't verified that.

I found that it's crashing in the following call in oauth2client\locked_file.py in the open_and_lock function:

hfile = win32file._get_osfhandle(self._fh.fileno())

**Comment by jonparrott** [comment]
More fuel for #470.

**Comment by yoursndv** [comment]
Thanks, adding  `sys.modules['win32file'] = None`  helped to overcome crash in Google API Client Library for Python ver.1.5.0  `discovery.build()`  call running on 64bit Anaconda Python 3.5 installation on Win10. 
Just to note: the same code was processed without crash on CPython 3.5 without this hack.

**Comment by jonparrott** [comment]
#470 is closed and this module no longer exists.
