### ISSUE TITLE
Clearer error messaging when token.uri.info is missing and retrieve_scopes() is called

### ISSUE THREAD

**Issue by kaliberto** [google/oauth2client#365]
When attempting to refresh the list of scopes available via credentials.retrieve_scopes() you receive the error AttributeError("'NoneType' object has no attribute 'find'",) if token.uri.info is not set on the credentials instance. It's not a very friendly error and it's unclear until you read the code that this value is not set when credentials are generated using flow_from_clientsecrets. When generating credentials from a OAuth2WebServerFlow this value is set to GOOGLE_TOKEN_INFO_URI.

I am not sure the thought process behind token.url.info being set for one flow type vs the other. In any case, better error handling would make the situation clearer.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
