### ISSUE TITLE
GoogleCredentials has an inappropriate relationship with its subclasses

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [google/oauth2client#388]
`GoogleCredentials` contains references to its subclasses; these references should be eliminated.

Why does anyone ever think implementation inheritance is a good idea?

**Comment by dhermes** [comment]
:+1:

**Comment by dhermes** [comment]
Original support added in #12 if it helps

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
