### ISSUE TITLE
Unable to switch abstract classes to use of abc module

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [google/oauth2client#393]
Since 2.6 the right way to write abstract classes in Python is with use of the `abc` standard library module. I took a stab today at converting `client.Credentials`, `client.Storage`, and `client.AssertionCredentials` to using `abc` and a bunch of tests failed with abstract-class-instantiation errors.

Which means that currently our tests instantiate nonsense partially-abstract objects and are totally cool with that. That is, in fact, not actually cool, and should be fixed.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
