### ISSUE TITLE
Reign in the service account constructor

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#422]
Two current scary points:
- The "secret" info (e.g. `_private_key_pkcs8_pem`) that has to be [copied over](https://github.com/google/oauth2client/blob/0c7996099f9e3d74f7b9a6d32b6f69f44987638a/oauth2client/service_account.py#L441-L443) in a manual way
- We allow a big surface ([all of [`kwargs`](https://github.com/google/oauth2client/blob/0c7996099f9e3d74f7b9a6d32b6f69f44987638a/oauth2client/service_account.py#L101)) for custom assertions when the `sub` field is likely the only extra one someone has used ([entire JWT assertion spec](https://tools.ietf.org/html/rfc7523)) This was supported in #420.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
