### ISSUE TITLE
Move DefaultCredential format and validation logic to default_credential_model module

### ISSUE THREAD

**Issue by 37thStreet** [google/oauth2client#44]
I was thinking of moving the DefaultCredential format definition and validation logic recently added to client.GoogleCredentials into a separate class. This predominantly concerns the validation code in _get_application_default_credential_from_file() starting here:
https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1162

What I'm hoping to accomplish:
- Consolidate the DefaultCredential format/model definition making it easier to implement and verify correctness of implementations in other languages
- Allow validation method to be called from non-file loader contexts
- Remove hardcoded strings for field names when serializing
- Add optional fields for token_uri and revoke_uri in the model and remove related references to constants in _get_application_default_credential_from_file()

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
