### ISSUE TITLE
Resolve ndb import failure in App Engine-like environments

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#440]
See [TODO](https://github.com/google/oauth2client/blob/d3a187c56a0e607030482ed33664cd7d335ea34c/oauth2client/contrib/appengine.py#L49-L50) (being removed in #434).

> Resolve import issue. This is a temporary fix for a Google internal issue.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
