### ISSUE TITLE
Allow setting user_agent in ServiceAccountCredentials.from_*

### ISSUE THREAD

**Issue by eesheesh** [google/oauth2client#445]
It should be possible to set the class's `_user_agent` when initializing it with `ServiceAccountCredentials.from_json_keyfile_name()` or the other similar methods.

This is a regression because `SignedJwtAssertionCredentials` allowed setting user_agent.

Thanks!

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
