### ISSUE TITLE
On refresh failures, is the store updated correctly?

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#480]
In the [error case](https://github.com/google/oauth2client/blob/043575aa8c08933a509b6b977c24ca1a7135daa8/oauth2client/client.py#L915-L928), the store is **only** updated with an invalid credential if the response is valid JSON and contains the key `error`. Shouldn't the credential be marked invalid and stored for all errors?

See #479.

/cc @nathanielmanistaatgoogle @jonparrott

**Comment by denniswambua** [comment]
Experiencing the same. I noticed that the refresh token is not being stored and this makes refreshing to fail.

:+1:

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
