### ISSUE TITLE
Remove http call in `gce.AppAssertionCredentials.service_account_email`

### ISSUE THREAD

**Issue by jonparrott** [google/oauth2client#523]
Only `refresh` should issue HTTP calls in credentials classes.

The credentials should be considered invalid until `refresh()` is called, and accessing `service_account_email` should return `None` until they are refreshed. This is in line with other classes' treatment of `scopes`.

(This is assigned to me, but @elibixby will primarily be doing this work)

**Comment by elibixby** [comment]
If we are ok with `None` returned from `service_account_email` and `scopes` this SGTM

I'll start work on this.

**Comment by jonparrott** [comment]
I'm fine with that, as long as the credentials appear invalid until refreshed.

@nathanielmanistaatgoogle @dhermes any objections?

**Comment by dhermes** [comment]
I'm not sure when they are used? I just added `service_account_email` to the GCE subclass to have consistent interfaces. This was part of the `ServiceAccountCredentials` rewrite that became 2.0.

**Comment by nathanielmanistaatgoogle** [comment]
No objection.

**Comment by jonparrott** [comment]
> I'm not sure when they are used?

If not by us, then just by users who want to get info about the service account they're using.

**Comment by elibixby** [comment]
Two points that came up while I was implementing this. 
*  `Credentials._retrieve_scopes` also provides a `Request` object, should we allow this function to validate the credentials as well (I think yes?)
*  Longer term, (and I'm fine with solving this problem when we get there), sign_blob is going to require an http request any way we slice it (since the metadata server or IAM API will be signing blobs for us). the `Credentials.sign_blob` method doesn't provide a `Request` object. Not sure if that effects preferred implementation details.
