### ISSUE TITLE
GoogleCredentials.get_application_default() fails to return the Appengine default service account in Flex environment

### ISSUE THREAD

**Issue by jamesawebb** [google/oauth2client#526]
From my investigations the error here is that the credentials object returned by the call to GoogleCredentials.get_application_default() is "effectively empty" - but not empty enough for the scope assignment to fail.  The library then tries to implicitly fetch the credentials from the environment in which it's running[1].  It does this in order of precedence:

        - Google App Engine (production and testing)
        - Environment variable GOOGLE_APPLICATION_CREDENTIALS pointing to
          a file with stored credentials information.
        - Stored "well known" file associated with `gcloud` command line tool.
        - Google Compute Engine production environment.

Because the scope is pseudo-empty - all these checks fail - up until the last check which determines whether a scope has been requested.  Because it has - the error you see[2] is returned.

External report at https://code.google.com/p/googleappengine/issues/detail?id=12970

[1] https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1382
[2] https://github.com/google/oauth2client/blob/master/oauth2client/contrib/gce.py#L69

**Comment by jonparrott** [comment]
I'm not sure I completely understand the issue here. I just tested and the Flexible environments gets application default credentials from the GCE metadata server as expected.

What's the expected behavior when you call `GoogleCredentials.get_application_default()` in GAE Flex? What behavior are you experiencing instead?

**Comment by arafuse** [comment]
The expected behavior on production GAE Flex is that the App Engine default service account should be fetched (as with GAE Standard), but instead it ends up fetching the service account for the underlying GCE instance.

This might normally be a benign issue, except that the GCE service account cannot be scoped, thus making it impossible for a flex app to set API scopes using the default credentials.

**Comment by jonparrott** [comment]
> The expected behavior on production GAE Flex is that the App Engine default service account should be fetched (as with GAE Standard), but instead it ends up fetching the service account for the underlying GCE instance.

I disagree, I think this is intended behavior. The GCE service account should be used.

> This might normally be a benign issue, except that the GCE service account cannot be scoped, thus making it impossible for a flex app to set API scopes using the default credentials.

You can set the scopes at the instance level in app.yaml, it's just not currently documented as we're trying to move away from scopes for service accounts towards IAM:

```
beta_settings:
  service_account_scopes: >
    https://www.googleapis.com/auth/userinfo.email,
    https://www.googleapis.com/auth/cloud-platform,
    ...
```
