### ISSUE TITLE
Can't safely deepcopy some credentials objects

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#549]
See [related thread](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1942/files/a62781c73fa1a86a278958c5db211a6a59234527#r71068638)

As mentioned there, I'm happy to tackle this if deemed important. We can define `__copy__` and `__deepcopy__`, should we also define a public `copy`?

/cc @waprin

**Comment by jonparrott** [comment]
Yep, seems reasonable. We have `to/from_json` already, it would be nice to formally support pickle, json, and copy semantics for all credentials.

**Comment by dhermes** [comment]
:-1: on `pickle`, but agree otherwise. Would love for one of these breaking releases to improve the serialization story (the "magic" import path stuff in the `Credentials.*_json` bases are too cute)

**Comment by jonparrott** [comment]
Pickle is used so much by Python standard libs it's hard for us to justify not supporting it. 

> Would love for one of these breaking releases to improve the serialization story

I'm cool with that, as long as @nathanielmanistaatgoogle is. He seems to be cool with me breaking bones left and right in contrib, but I'm unsure how he feels about mucking about the core.

(I think we'll be at oauth2client 30.0.0 before I'm happy with this library)

> too cute

You and I have very different definitions of cute. :)

**Comment by nathanielmanistaatgoogle** [comment]
Having read the serialization chapter of _Effective Java_ I pretty much have contempt for `pickle`... and that means I don't much care about breaking it from one version to the next. Go to town!

**Comment by pferate** [comment]
I think I got a working solution for this, but wanted to get some feedback.  It looks like the `_cffi_backend` errors come up when trying to copy the public and private keys in the `OpenSSLSigner` and `OpenSSLVerifier` objects; `Rsa*` and `PyCrypto*` objects are not affected.

I can add a very trivial `__deepcopy__` method to those 2 classes, which just creates a new `OpenSSL*` object, but would use the same public and private key object, so that wouldn't be be a true deep copy.

Instead, I added a `__deepcopy__` to `ServiceAccountCredentials`, which is a normal `deepcopy`, but for the `_signer` object, I create a new `OpenSSLSigner` object.  All other attributes handle `deepcopy` just fine.

This way allows for deepcopying the Credentials objects, but not for the Signer or Verifier objects, which don't store the private/public key strings or passwords.  I think that would be an acceptable solution, but that's not up to me.

**Comment by dhermes** [comment]
@pferate That's what I was planning on doing

**Comment by pferate** [comment]
So digging deeper into the `OpenSSLSigner` and `OpenSSLVerifier` classes, it is the private and public key attributes that don't allow the `deepcopy`.  Those keys are `OpenSSL.crypto.PKey` objects.

Looks like the `ServiceAccountCredentials` class doesn't have strong enforcement of maintaining any of the `_private_key_pkcs8_pem`, `_private_key_pkcs12`, or `_private_key_password` attributes.  This makes it difficult to create an entirely new `OpenSSLSigner` object.

It looks like if you create the credentials using one of the `from_json_keyfile_*` or `from_p12_keyfile*` class methods, those attributes get assigned, assuming they are defined in the input file.  They could also be defined after the object gets created, as shown in some of the samples.

How should the `__deepcopy__` handle the cases where it can't create a completely new `Signer` object?  Raise an exception?  Or create a new `Signer` object that uses the a shallow copy of the `PKey` object?

**Comment by dhermes** [comment]
> This makes it difficult to create an entirely new `OpenSSLSigner` object.

IMO two things should happen

1. We should just re-use the `OpenSSLSigner` object
1. We should use the new copy methods and more strongly enforce / maintain all the properties of `ServiceAccountCredentials`

**Comment by pferate** [comment]
1.  That would work, it just wouldn't be a deep copy.
2.  Wouldn't `__copy__` do that for all items in `Credentials.__dict__`?  Are there some properties that we wouldn't want or care to be copied?

**Comment by dhermes** [comment]
I think we can call it effectively a deep copy. What are the implications if the key is shared by two objects?

**Comment by pferate** [comment]
If you run `generate_key()` or modify one of the keys without redefining it, all of the copied objects will get their keys updated as well.  It may be a very minority situation, and I'm not sure how realistic it would be.

```python
signer1 = crypt.OpenSSLSigner.from_string(private_key1)
signer2 = copy.copy(signer1)
signer3 = copy.deepcopy(signer2)
# Generate new key, affects all related objects
signer3._key.generate_key(type=OpenSSL.crypto.TYPE_RSA, bits=2048)
```
With them sharing the same `PKey` object, the last line in the example will update the keys for `signer1` and `signer2`.  This can be avoided by the developer by creating a new `PKey` object before generating a new key.

```python
signer1 = crypt.OpenSSLSigner.from_string(private_key1)
signer2 = copy.copy(signer1)
signer3 = copy.deepcopy(signer2)
# Create new PKey before generating new key, only affects signer3
signer3._key = OpenSSL.crypto.PKey()
signer3._key.generate_key(type=OpenSSL.crypto.TYPE_RSA, bits=2048)
```

**Comment by pferate** [comment]
@dhermes (re: to your update) That is true for the `OpenSSLSigner` and `OpenSSLVerifier` classes.  _Some_ of the constructors for `ServiceAccountCredentials` store the data needed to recreate the signer object, and in those few cases, it is only if the needed information is being passed in.

**Comment by pferate** [comment]
I suppose that we can say that if the developer is going to be modifying "private" properties (`OpenSSLSigner._key`), then they should be responsible for doing it correctly.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
