### ISSUE TITLE
Make sure imported functions / classes are public

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#580]
This is @nathanielmanistaatgoogle's preference, maybe he can elaborate.

AFAIK this only applies to things like `_helpers._from_bytes` which can safely be `_helpers.from_bytes` without being public

**Comment by nathanielmanistaatgoogle** [comment]
Of course what really matters is library-public versus library-private.

Extending the convention to the library's own internal modular boundaries and abstractions is good for uniformity and helps us clearly state (to each other and to our future selves) our expectations for how code elements are used.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
