### ISSUE TITLE
Add timeout argument to transport.request

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#618]
See https://github.com/google/oauth2client/pull/612#discussion_r74455264

It's unclear if an `httplib2.Http` request can be made with a timeout if the instance wasn't created with one, though likely it could be fixed with

``` python
orig_timeout = http.timeout
try:
    http.timeout = temp_value
    do_stuff(http)
finally:
    http.timeout = orig_timeout
```

More problematic is when `http.request` has been modified (by our wrappers) and we are unsure what has been passed to `transport.request` (though I have an idea there).

**Comment by jonparrott** [comment]
Depending on the decision in #128 we could have the guarantee that `request` hasn't been modified by our wrapper.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
