### ISSUE TITLE
save_to_well_known_file() takes only GoogleCredentials

### ISSUE THREAD

**Issue by skelterjohn** [google/oauth2client#62]
This function should probably take any sort of Credentials object, and either convert or raise an exception, depending on which type comes in.

**Comment by filbranden** [comment]
+1. This is a terrible API.

In particular, looking inside the code behind `gcloud auth login`, it needs to convert the OAuth2Credentials into a GoogleCredentials and does it with:

```
      google_creds = client.GoogleCredentials(
          creds.access_token, creds.client_id, creds.client_secret,
          creds.refresh_token, creds.token_expiry, creds.token_uri,
          creds.user_agent, creds.revoke_uri)
      try:
        client.save_to_well_known_file(google_creds)
```

Inheritance is clearly all wrong here... For more details, check [this talk](https://www.youtube.com/watch?v=3MNVP9-hglc) (from some fellow Googlers) about how problems created by inheritance.

Also, staticmethods are wrong, you should just stop using them here.

I'd be happy to do code reviews for changes in this area.

Thanks!
Filipe

**Comment by dhermes** [comment]
FWIW the `staticmethod`s were part of an effort to slowly fix up a pre-existing code stew. The effort stalled in its tracks but someone else is free to take it up. I agree with all your points and wonder why the original authors didn't put the Application Default Credentials stuff in its own module.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
