### ISSUE TITLE
Make tox django matrix

### ISSUE THREAD

**Issue by waprin** [google/oauth2client#620]
Good to test all combos of py27,py35 x django1.8-django1.10

**Comment by dhermes** [comment]
Fine in `tox` but :-1: on doing that on Travis, since every env. gets treated like it's own job, there could be throttling.

Also, what is the "recommended" way to be compatible with `django` (i.e. which versions)?

**Comment by waprin** [comment]
Hmm ok, we can also run the tests on our internal Jenkins. Been procrastinating some feature improvements like Github PR building and badges (behind firewall so have to configure plugins accordingly) but I'm going to get around to it sooner or later.

https://www.djangoproject.com/download/ shows supported versions. I think the logical strategy is the supported versions, which nowadays is 1.08 (LTS) to 1.10.

**Comment by waprin** [comment]
Just to clarify, the way the Jenkins build will work is it will just upload the build output to a bucket for viewing, so we won't provide external access but will provide access to all the relevant information. General strategy for our team which I think makes sense here as well is that Travis is higher priority and first choice, but we offload some of the load to Jenkins when necessary.

**Comment by jonparrott** [comment]
We already run the compute engine system test on Jenkins, so.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
