### ISSUE TITLE
Set-up AppVeyor CI

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#633]
Was #491 but @jonparrott blew it up, oh noes!

This will ~~allows~~ allow Windows testing

**Comment by jonparrott** [comment]
Sounds reasonable.

**Comment by dhermes** [comment]
https://packaging.python.org/appveyor/ and https://github.com/ogrisel/python-appveyor-demo very helpful here

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
