### ISSUE TITLE
Add OS X to Travis

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#634]
See https://docs.travis-ci.com/user/multi-os/ and https://docs.travis-ci.com/user/osx-ci-environment/

Note in particular that

> If you are already using a [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) to test multiple versions, the `os` key also multiplies the matrix.

which would grow the already hefty matrix from 10 to 20. (IIRC each env in the matrix gets treated as a job when doing Travis scheduling, so it may make sense to collapse the matrix. But I may be wrong.)

Relates to #633

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
