### ISSUE TITLE
xsrfutil.py validate_token() 

### ISSUE THREAD

**Issue by wasabigeek** [google/oauth2client#637]
I'm trying to use the oauth2client/oauth2client/contrib/xsrfutil.py with Django, but get this error when using `validate_token()`: "string argument without an encoding". From the stacktrace it looks like this is the line causing the error: https://github.com/google/oauth2client/blob/master/oauth2client/contrib/xsrfutil.py#L99

I think the problem is with the `token` parameter, which is a string. For [bytearray](https://docs.python.org/3.4/library/functions.html#bytearray) we need to specify the encoding.

Python versions attempted: 2.7.11, 3.4
Django versions attempted: 1.8, 1.9.9, 1.10

**Comment by jonparrott** [comment]
Looks like `generate_token` will return a bytestring. Are you sure you're passing a bytestring into `validate_token`?

**Comment by wasabigeek** [comment]
In the [code comments](https://github.com/google/oauth2client/blob/master/oauth2client/contrib/xsrfutil.py#L69) it says the parameter should be a regular string, will try using a bytestring later.

**Comment by jonparrott** [comment]
@wasabigeek bump, is this still an issue?

**Comment by wasabigeek** [comment]
@jonparrott sorry haven't tried it - I've been using the decorator instead https://github.com/google/oauth2client/pull/636/files#diff-de2fc5853437bc87b3335ca6d764cf40R24

**Comment by ulope** [comment]
Just ran into this as well. In the django example the `state` value is passed directly from the `request` - which is always a string. A workaround is to first `.encode('UTF-8')` the value.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
