### ISSUE TITLE
AttributeError when library called from embedded Python (missing sys.argv)

### ISSUE THREAD

**Issue by sahuguet** [google/oauth2client#642]
When the library is used with embedded Python (e.g. Postgres extension written in C calling Python, like Multicorn), sys.argv is not defined, which makes the library misbehave, see below.

```
      File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 83, in _CreateArgumentParser
        parser = argparse.ArgumentParser(add_help=False)

      File "/usr/lib/python2.7/argparse.py", line 1575, in __init__
        prog = _os.path.basename(_sys.argv[0])

    AttributeError: 'module' object has no attribute 'argv'

```

**Comment by filipstachura** [comment]
Workaround is to start embedded script with:
```
import sys

if not hasattr(sys, 'argv'):
    sys.argv  = ['']
```

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
