### ISSUE TITLE
Rename to_json/from_json as json_serialize/json_deserialize

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#644]
People often get these confused with methods they should actually be using.

**Comment by jonparrott** [comment]
Do we want to wait to do this for the post-4.0.0 refactor or would you rather do it before/with 4.0.0?

**Comment by dhermes** [comment]
before/with

**Comment by souravbadami** [comment]
@jonparrott -- Can I take this one ?

**Comment by jonparrott** [comment]
@souravbadami I appreciate the offer, but at this point we will not be making any more major releases to this library, so it's unlikely we'll merge a breaking change.

**Comment by souravbadami** [comment]
@jonparrott -- Ah, Okay!

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
