### ISSUE TITLE
Drop casting of status codes to integers throughout client.py and elsewhere

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#656]
I vaguely remember a PR that added all of this, but can't remember the why.

**Comment by nathanielmanistaatgoogle** [comment]
I don't yet understand what this issue is about - link to a line number that would be changed?

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle You can see a line where I [referenced][1] this issue in #654 (though the "@dhermes referenced..." link doesn't go straight there).

[Here][2] is the line in question. Maybe @jonparrott can give some other links for the other places it is sprinkeld.

[1]: https://github.com/google/oauth2client/pull/654#discussion_r79891736
[2]: https://github.com/google/oauth2client/blob/3f9fdbd5a3e590e6e53e42a59ca96d1010c0cec7/oauth2client/client.py#L2075

**Comment by pferate** [comment]
I vaguely remember adding this.  This was due to a change in 3.4 or 3.5, where the built-in HTTP Client went from return Integers to a new HttpStatus object.  Casting to integers was done to be able to have everything consistent.

**Comment by pferate** [comment]
[http.HTTPStatus](https://docs.python.org/3.5/library/http.html#http.HTTPStatus) was added in 3.5.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
