### ISSUE TITLE
Prettify stored credentials

### ISSUE THREAD

**Issue by jay0lee** [google/oauth2client#669]
Currently, credentials are stored as minimal JSON. This makes it a challenge when a developer needs to peek at credentials stored to a file in order to find their project_id, client_id, refresh_token or some other detail.

We should be able to pretty print the JSON before storage to make it easier for human eyes to read.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
