### ISSUE TITLE
jsonpickle isn't a dependency?

### ISSUE THREAD

**Issue by john2x** [google/oauth2client#681]
I'm getting `ImportError: No module named jsonpickle` with Python 2.7 and the `django_util` module using version `4.0.0`. #672 and #676 seem to suggest that `jsonpickle` should already be a dependency, but it isn't listed in `setup.py`?

**Comment by waprin** [comment]
Yeah, it should probably be a dependency. It was procrastinated because we've discussed making the whole django package optional, but in the meantime, prob best to just put it in there. Will run it by @jonparrott in the morning.

**Comment by john2x** [comment]
Ok, cool. I'll just specify it in my project's dependencies for the meantime.

**Comment by srcreigh** [comment]
FYI, just ran into this.

**Comment by fixmycode** [comment]
@srcreigh apparently the developers turned to `google-auth` and `OAuthlib`, but this pair doesn't cover all the use cases that `oauth2client` covered, specifically the Django integration. I'll make a pull request later adding the package to the setup.py and a maintainer could upload the new version to PyPI.

**Comment by jonparrott** [comment]
@fixmycode thanks for the offer, but we won't be releasing new versions.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
