### ISSUE TITLE
Load settings lazily

### ISSUE THREAD

**Issue by bboogaard** [google/oauth2client#684]
Would you consider changing the django integration in such a way that the api credentials are not needed compile time (e.g. by wrapping the instantiation of OAuth2Settings in a SimpleLazyObject).

Or is there another way of skipping the loading of client secrets whenever I import oauth2client.contrib.django_util?

**Comment by jonparrott** [comment]
/cc @waprin 

This is unlikely, as we're starting to severely limit new features or refactors in this library.

**Comment by waprin** [comment]
It's a good suggestion, but this library is being replaced by https://github.com/GoogleCloudPlatform/google-auth-library-python . I think @jonparrott has mentinoed existing Django libraries should more naturally integrate with (still need to try it out myself).

As far as your suggestion, it's a good idea but because of the above unlikely I'll get to it. If you make a  PR I'd be happy to review it though, and I think @jonparrott would be down to accept it.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
