### ISSUE TITLE
Obtain service credentials from dict

### ISSUE THREAD

**Issue by AP-e** [google/oauth2client#685]
Is there a way to supply a dict to `oauth2client.client.flow_from_clientsecrets()` to create a Flow object without reference to the service account .JSON file? My understanding is that this restriction prevents the storage of sensitive information in code, however it seems possible for this file to be unintentionally exposed via source control or otherwise compromised. My current workaround, when deploying to Heroku, involves reconstruction of the credentials file from environment variables.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
