### ISSUE TITLE
Is django_orm deprecated?

### ISSUE THREAD

**Issue by Cosbgn** [google/oauth2client#686]
from [change log](https://github.com/google/oauth2client/blob/master/CHANGELOG.md) of V.2.2.0 I read:` oauth2client.contrib.django_util and oauth2client.contrib.django_orm have been updated to support Django 1.8 - 1.10.`

However `django_orm` is not in the source code and obviously I get an `import error` when running `from oauth2client.contrib.django_orm import CredentialsField`

Is this deprecated or I need to import something else? I guess then [this official Google guide](https://developers.google.com/api-client-library/python/guide/django) is outdated, right?

**Comment by waprin** [comment]
@Cosbgn the docs you link to are out of date. This repo has the more [up to date docs](https://oauth2client.readthedocs.io/en/latest/). We do need to update those docs, but in general we're moving away from this library and towards [this one](https://github.com/GoogleCloudPlatform/google-auth-library-python). Sorry for the confusion, planning to take another pass at those docs soon.

**Comment by Cosbgn** [comment]
Perfect, would be great if you could add a notification or something in the site, as those are the "official links" and I guess it might confuse a lot of users. 

Just to have more clear ideas, in order to login & do some analysis to user's Google Analytics data e.g a dashboard, should I use the `auth2client` or the `Google Auth Python Library` ?

Thanks!

**Comment by jonparrott** [comment]
For google analytics you should stuck to oauth2client for the time being.

**Comment by Cosbgn** [comment]
Great thanks

**Comment by danyaljj** [comment]
Outdate docs waster lots of time from me ....

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
