### ISSUE TITLE
Mandatory slash at the end of oauth_callback URI is incompatible with Google Dev Console credential settings

### ISSUE THREAD

**Issue by akalmykov** [google/oauth2client#700]
Mandatory slash at the end of oauth_callback URI is incompatible with Google Dev Console credential settings. In Google Dev console Credential one cannot register a call back URL that end with a slash. But oath client inserts the slash, leading to Error: redirect_uri_mismatch

The slash shouldn't be mandatory in oath2 client. Or should be allowed in Google Dev Console settings.

This can be reproduced by running any example for python api client, e.g.
https://github.com/youtube/api-samples/blob/master/python/upload_video.py

The issue is in tools.py:

```
    if not flags.noauth_local_webserver:
        oauth_callback = 'http://{host}:{port}/'.format(
            host=flags.auth_host_name, port=port_number)

```

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
