### ISSUE TITLE
When performing grant_type=refresh_token, the "Authorization: Bearer..." header is applied

### ISSUE THREAD

**Issue by wtfrank** [google/oauth2client#706]
I'm not sure it makes sense to be authorizing with a probably-expired access token in the header, at the same time that in the body you are passing the client id+secret and requesting a new access token

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
