### ISSUE TITLE
Add deprecation notice to docs.

### ISSUE THREAD

**Issue by tswast** [google/oauth2client#715]
oauth2client is now deprecated, but when I look at https://oauth2client.readthedocs.io/en/latest/, I wouldn't know.

**Comment by techiesse** [comment]
Also in the api client documentation it is recomending the deprecated version: https://developers.google.com/api-client-library/python/guide/django

**Comment by parity3** [comment]
Is there a blog post or a rant from someone making the decision to deprecate an entire library silently without updating the documentation of several official google docs?

**Comment by jonparrott** [comment]
@parity3 there's some google-internal documentation on why we deprecated. I'll get a distilled version published on the new library's documentation.

**Comment by jonparrott** [comment]
See https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/165

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!

**Comment by tswast** [comment]
Running a script @theacodes ? This does appear to still be relevant, as I still don't see a deprecation notice linking to `google-auth` at https://oauth2client.readthedocs.io/en/latest/

**Comment by theacodes** [comment]
It's in our readme, but not in docs.

Fixed it https://github.com/google/oauth2client/commit/0d1c814779c21503307b2f255dabcf24b2a107ac
