### ISSUE TITLE
Secret is logged in crypt.py

### ISSUE THREAD

**Issue by faizalkassamalisc** [google/oauth2client#727]
**Note**: oauth2client is now deprecated. As such, it is unlikely that we will
address or respond to your issue. We recommend you use
[google-auth](https://google-auth.readthedocs.io) and [oauthlib](http://oauthlib.readthedocs.io/).

https://github.com/google/oauth2client/blob/master/oauth2client/crypt.py#L100

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
