### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level (reauth_creds.py, line 136)

### ISSUE THREAD

**Issue by pablopla** [google/oauth2client#732]
google-cloud-sdk still uses this library.

I'm getting the following error on Ubuntu-16.04:
```bash
Setting up google-cloud-sdk (182.0.0-0) ...
Compiling lib/third_party/oauth2client/contrib/reauth_creds.py ...
Sorry: IndentationError: unindent does not match any outer indentation level (reauth_creds.py, line 136)
```
Installing with:
```bash
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install google-cloud-sdk
```

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
