### ISSUE TITLE
Remove enforcement of django.sessions in middleware

### ISSUE THREAD

**Issue by snoepkast** [google/oauth2client#733]
Hey there,

I just updated to the latest version of the package since I noticed that the storage didn't get properly saved in the CredentialsField, which resulted in always needing to refresh before doing any requests. But I can't test if new version fixes it for me.

We use [django-user-sessions](https://pypi.python.org/pypi/django-user-sessions) instead of the default django sessions. This is a drop-in replacement so everything should work, however there is an if check [here](https://github.com/google/oauth2client/blob/master/oauth2client/contrib/django_util/__init__.py#L354) which breaks everything.

My proposal is to remove the if check and assume people have their project configured properly, if not the resulting error should be obvious anyway.

I know this package is deprecated, but moving to google-auth is not an option for us at this time, and this change should not break backwards compatibility.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
