### ISSUE TITLE
Error with from_json

### ISSUE THREAD

**Issue by wkaisertexas** [google/oauth2client#735]
So, I am using oauth2client in order to use a google drive api and I get this weird error.

Traceback (most recent call last):
  File "C:/Users/Will Kaiser's PC/Documents/PyCharm/Projects/ph/main.py", line 16, in <module>
    creds = ServiceAccountCredentials.from_json('client_secret', scope)
TypeError: from_json() takes 2 positional arguments but 3 were given

It says 3 arguments were given yet the code only has 2 arguments. Does anyone know why this is

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecated
and we will only be addressing critical security issues. You can read more
about this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask your
question on StackOverflow.

If you still think this issue is relevant and should be addressed, please
comment and let us know!

**Comment by lepture** [comment]
Just a note here. If anyone is looking for another alternative, check out https://github.com/lepture/authlib

Here are some tips on how to use Authlib with Google services:

1. https://blog.authlib.org/2018/access-google-analytics-api
2. https://blog.authlib.org/2018/multipart-upload-to-google-cloud-storage
3. https://blog.authlib.org/2018/authlib-for-gspread
