### ISSUE TITLE
Detecting GCE sometimes takes forever.

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#93]
on some networks (@dhermes has one at home), doing a lookup on a bogus URL takes ~20-30s. this means that the default way of discovering the current environment (say for fetching the application default credential) can be insanely slow.

**Comment by craigcitro** [comment]
@aaronwinter in this case, we know what IP the hostname resolves to, so i think we *don't* want to go the twisted/dnspython route. 

i think the best solution on the table is a three-pronged attack:
 * refactor the code a bit so that we can avoid the GCE check in more cases,
 * possibly switch to using the IP with a **short** timeout, and 
 * add an env var that says "i'm definitely not on gce, don't bother checking".

**Comment by craigcitro** [comment]
The first step (switch to the IP for the metadata service) is bf9d46e.

**Comment by aaronwinter** [comment]
Ok, thanks for the directions! Do you want the env var to be set to ~"no need to check" once a negative check has been done or something that is by default to "not check gce" and that the user will need to modify to enable gce checking?

**Comment by dhermes** [comment]
@craigcitro Care to close this out?

**Comment by craigcitro** [comment]
@dhermes i figured we'd leave it until all the steps above were done, but maybe we should track those separately ...

**Comment by dhermes** [comment]
Which steps remain? You referring to #111?

I like to use check-marks to track a plan of work in progress (see GoogleCloudPlatform/gcloud-python#451 for example).

**Comment by aaronwinter** [comment]
@dhermes I think @craigcitro is referring to this one:

> refactor the code a bit so that we can avoid the GCE check in more cases,

For future reference:

- [  ] refactor the code a bit so that we can avoid the GCE check in more cases,
- [x] possibly switch to using the IP with a short timeout 
- [x] add an env var that says "i'm definitely not on gce, don't bother checking".

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
