### ISSUE TITLE
Enable GAE-related tests.

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#96]
This repo contains a number of tests of `oauth2client/appengine.py`, but they're currently disabled in tox/travis. We should download the SDK and re-enable them.

**Comment by dhermes** [comment]
FYI I have enabled this in a [personal project][1].

Some keys to do this:

In `.travis.yaml`:

```
language: python
sudo: false
cache:
  directories:
  - cache/

before_install:
  - ./get_app_engine_sdk.sh
  - export GAE="./cache/google_appengine"

...
```

which uses a `get_app_engine_sdk.sh` bash [script][2] to retrieve a specific version of the SDK.

Then to actually enable the imports, each module which requires App Engine uses

```python
from google_imports import urlfetch
```

instead of

```python
from google.appengine.api import urlfetch
```

The final piece of the puzzle (which relies on the `GAE` environment variable) comes in [`google_imports.py`][3]:

```python
import os
import sys


def get_appengine_path():
  gae_path = os.getenv('GAE')
  if gae_path is None:
    raise EnvironmentError('Google App Path not found.')
  return gae_path


def set_appengine_imports():
  gae_path = get_appengine_path()
  sys.path.insert(0, gae_path)
  sys.modules.pop('google', None)
  import dev_appserver
  dev_appserver.fix_sys_path()


set_appengine_imports()
```

[1]: https://github.com/dhermes/ndb-git
[2]: https://github.com/dhermes/ndb-git/blob/d5cfbfadaea90f2b87f1b3ed7ea663008038c668/get_app_engine_sdk.sh
[3]: https://github.com/dhermes/ndb-git/blob/d5cfbfadaea90f2b87f1b3ed7ea663008038c668/ndb/google_imports.py

**Comment by craigcitro** [comment]
grin ... i think i wrote a roughly equivalent python script, which now lives at `scripts/fetch_gae_sdk.py`.

**Comment by dhermes** [comment]
Yeah that part is easy, I had to make a lot of false starts before getting `cache/` right.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
